- jokes/index.json
Hi, 
This is my first open source pull request. I read the README.md file, and created a new joke using the format as requested. Please let me know if I missed a step in the process. If not, I have a ton more to add to the list! :)
> added joke index 31

- jokes/index.json
A joke that I like to tell to my co-workers sometimes. Think it's quite funny.
> adding expection joke

- jokes/index.json
> Added New Jokes

- jokes/index.json
> added joke 59

- jokes/index.json
> added joke 58

- jokes/index.json
> What do you give to a lemon in need?

- README.md
- jokes/index.json
no need for quotes in id
also added 4 jokes
> Fixed Readme and added 3 jokes

- jokes/index.json
About 1/2 we're already in a 2 part format.
It seems my json formatter corrected some spacing on a few older questions.
> Added lots of jokes from icanhazdadjoke.com

- handler.js
- index.js
new endpoint = /jokeByType/:type
e.g. /jokeByType/programming
e.g. /jokeByType/general
/jokeByType/ without type fails
/jokeByType/blah (mispelled or type that doesnt exist) returns a random joke from the entire list
> added jokeByType

- jokes/index.json
I added some new programming jokes I found scattered across different internet sources, including a large programming jokes thread on reddit:  [reddit source](https://www.reddit.com/r/AskReddit/comments/1kvhmz/whats_the_best_programming_joke_that_you_know/)
> Added a few programming jokes

- handler.js
Allow access to the entire jokes array, as well as the randomN method
> Export jokes and randomN

- jokes/index.json
Fixes #49 
Deduping the joke about holy water.
> chore: remove duplicate joke

- jokes/index.json
This accomplishes 2 things. 
1. A new joke added
2. You jokes were duplicate initially 36 and 37 (issue #74), not anymore.
> Added a general joke at 37

- jokes/index.json
Merging https://github.com/15Dkatz/official_joke_api/pull/79
> Gacurl patch 1

- jokes/index.json
Merging https://github.com/15Dkatz/official_joke_api/pull/78
> Add a joke

- jokes/index.json
Merge https://github.com/15Dkatz/official_joke_api/pull/77
> resolve conflicts

- jokes/index.json
> Fixed Duplicate Jokes

- jokes/index.json
Some strings have trailing spaces at the start. This PR removes them.
> Remove trailing spaces in some strings

- jokes/index.json
Added 4 Programming Jokes at the end of the file.
> Updated index.json

- jokes/index.json
Added a few React jokes as my first contribution to open source.
> Added jokes

- jokes/index.json
Added programming and general jokes.
> Adding jokes/programming and general

- jokes/index.json
I didn't fully understand this joke so I did some digging and I think I understand it now. But if this is a "whoosh" moment on my part, just know I have sincere intentions lol.
I'm proposing we remove this joke for two reasons:
1. It's not widely accessible because It requires the listener to understand Indian names and meanings to get that the punchline.
2. While the joke paints female developers in a positive light, it still has a womanizing tone that I don't think everyone receives well. I think it would be better to just steer clear from jokes involving gender at all.
> Removed Context-Heavy Joke

- index.js
Thank you for your course!
This is just a test pull for Github. For educational purposes.
No need to approve the pull.
More power!
> Added a space in the end

- jokes/index.json
This is my first ever contribution to a git repo. I added 25 jokes.
> added 25 jokes
